//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifastats1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spielergebnisse
    {
        public int SpielID { get; set; }
        public Nullable<int> Tore { get; set; }
        public Nullable<int> Gegentore { get; set; }
        public Nullable<int> MannschaftsID { get; set; }
        public Nullable<int> FormationsID { get; set; }
    
        public virtual Formationen Formationen { get; set; }
        public virtual Mannschaften Mannschaften { get; set; }
    }
}
